name: BYOND Compile CI
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    container: 
      image: tgstation/byond:513.1527
      volumes:
        - $GITHUB_WORKSPACE:/mnt
    strategy:
      fail-fast: false
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Run Dream Maker
      id: compile
      run: DreamMaker /mnt/*.dme