name: BYOND Compile CI
on: [push, pull_request]
jobs:
  Compile:
    runs-on: ubuntu-latest
    container: 
      image: tgstation/byond:513.1536
    strategy:
      fail-fast: false
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    
    - name: Run Dream Maker
      id: compile
      run: DreamMaker *.dme
