name: BYOND Compile CI
on: [push]
jobs:
  Compile:
    runs-on: ubuntu-latest
    container: 
      image: tgstation/byond:513.1527
    strategy:
      fail-fast: false
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    
    - name: Run Dream Maker
      id: compile
      run: DreamMaker *.dme