name: BYOND Compile CI
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    container: 
      image: tgstation/byond:513.1527
    strategy:
      fail-fast: false
    steps:
    - name: Install Git
      run: |
        apt update
        apt install -y git
        if ! apt list --installed 2>/dev/null | grep -q "git.*"; then
          apt install -y git
        elif apt list --installed 2> /dev/null | grep -q "git.*"; then
          true
        else
          exit 255
        fi

    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Run Dream Maker
      id: compile
      run: DreamMaker /mnt/*.dme